version: "3.3"

services:
  # Use admin/admin as username/password
  grafana:
    container_name: grafana-localhost
    image: grafana/grafana:9.4.7
    restart: always
    ports:
      - 3000:3000
    environment:
      GF_SERVER_ROOT_URL: http://172.16.1.5

  prometheus:
    container_name: prometheus-localhost
    image: prom/prometheus:v2.43.0
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090

  prometheus-node-exporter:
    container_name: prometheus-node-exporter-localhost
    image: prom/node-exporter:v1.5.0
    restart: always
    depends_on:
      - prometheus
    ports:
      - 9100:9100
